import Image from "next/image";
import Link from "next/link";
import type { Issue } from "@/content/issues";

export function IssueHeader({ issue }: { issue: Issue }) { return <div className="issue-meta"><span>Vol. IX · No. {issue.issueNumber}</span><strong>{issue.week} · {issue.season}</strong><span>{issue.date}</span></div>; }

export function Scoreboard({ issue }: { issue: Issue }) { return <section className="section-block" aria-labelledby="scoreboard-title"><div className="section-title"><span>Results</span><h2 id="scoreboard-title">The Scoreboard</h2></div><div className="score-grid">{issue.results.map((game) => { const awayWins = game.awayScore > game.homeScore; return <article className="matchup" key={game.away}><div><span className={awayWins ? "winner" : ""}>{game.away}</span><strong>{game.awayScore.toFixed(2)}</strong></div><div><span className={!awayWins ? "winner" : ""}>{game.home}</span><strong>{game.homeScore.toFixed(2)}</strong></div>{game.note && <p>{game.note}</p>}</article>; })}</div></section>; }

export function StandingsTable({ issue }: { issue: Issue }) { return <section className="standings" aria-labelledby="standings-title"><div className="section-title compact"><span>After Week 1 · Median 135.90</span><h2 id="standings-title">Standings</h2></div><div className="table-wrap"><table><thead><tr><th>#</th><th>Club</th><th>Rec.</th><th>PF</th><th>PA</th></tr></thead><tbody>{issue.standings.map((row) => <tr key={row.team}><td>{row.rank}</td><th>{row.team}</th><td>{row.record}</td><td>{row.points.toFixed(2)}</td><td>{row.pointsAgainst.toFixed(2)}</td></tr>)}</tbody></table></div></section>; }

export function PowerRankings({ issue }: { issue: Issue }) { return <section className="rankings" aria-labelledby="rankings-title"><div className="section-title compact"><span>Editorial Board</span><h2 id="rankings-title">Power Five</h2></div>{issue.rankings.map((row) => <article key={row.team}><b>{row.rank}</b><div><h3>{row.team}</h3><p>{row.blurb}</p></div></article>)}</section>; }

export function WeeklyAwards({ issue }: { issue: Issue }) { return <section className="awards section-block" aria-labelledby="awards-title"><div className="section-title"><span>Honor & Infamy</span><h2 id="awards-title">The Weekly Laurels</h2></div><div className="award-grid">{issue.awards.map((award) => <article key={award.label}><span>{award.label}</span><h3>{award.winner}</h3><p>{award.detail}</p></article>)}</div></section>; }

function PositionLeaders({ issue }: { issue: Issue }) { return <section className="leaders section-block" aria-labelledby="leaders-title"><div className="section-title"><span>Players of the Week</span><h2 id="leaders-title">The Five Who Owned Sunday</h2></div><div className="leader-grid">{issue.leaders.map((leader) => <article key={leader.position}><b>{leader.position}</b><div><h3>{leader.player}</h3><p>{leader.team}</p><strong>{leader.points.toFixed(2)}</strong></div></article>)}</div></section>; }

function HistoryLedger({ issue }: { issue: Issue }) { return <section className="history section-block" aria-labelledby="history-title"><div className="section-title"><span>Year XVI</span><h2 id="history-title">The Active-Member Ledger</h2></div><p className="section-intro">The league has welcomed 34 managers since 2011. These are the established A League résumés entering the 2026 season; the four newly promoted clubs begin writing theirs now.</p><div className="table-wrap"><table><thead><tr><th>Manager</th><th>Current Club</th><th>Titles</th><th>Playoffs</th><th>Historical Note</th></tr></thead><tbody>{issue.history.map((row) => <tr key={row.manager}><th>{row.manager}</th><td>{row.club}</td><td>{row.titles}</td><td>{row.playoffs}</td><td>{row.note}</td></tr>)}</tbody></table></div></section>; }

export function NewspaperIssue({ issue }: { issue: Issue }) { return <main id="main-content" className="paper"><IssueHeader issue={issue}/><header className="front-page-head"><p>{issue.kicker}</p><h1>{issue.headline}</h1><h2>{issue.deck}</h2></header><figure className="lead-image"><Image src={issue.hero} alt={issue.heroAlt} width={1536} height={1024} priority/><figcaption>{issue.caption}</figcaption></figure><div className="front-grid"><article className="lead-copy"><p className="byline">By The Chronicle Sports Desk</p>{issue.lead.map((p, i) => <p className={i === 0 ? "dropcap" : ""} key={p}>{p}</p>)}<blockquote>“{issue.quote}”<cite>— {issue.quoteBy}</cite></blockquote></article><aside className="briefs"><h2>News Briefs</h2>{issue.briefs.map((brief) => <article key={brief.headline}><h3>{brief.headline}</h3><p>{brief.body}</p></article>)}</aside></div><Scoreboard issue={issue}/><div className="analysis-grid"><StandingsTable issue={issue}/><PowerRankings issue={issue}/></div><section className="story-section section-block"><div className="section-title"><span>Around the League</span><h2>Dispatches From Year Sixteen</h2></div><div className="story-grid">{issue.stories.map((story) => <article key={story.headline}><span>{story.section}</span><h3>{story.headline}</h3><p>{story.body}</p></article>)}</div></section><PositionLeaders issue={issue}/><WeeklyAwards issue={issue}/><HistoryLedger issue={issue}/><section className="next-week"><span>Coming Sunday</span><h2>Week 2: The New Order Gets Tested</h2><p>Five clubs are perfect, four promoted managers have announced themselves, and the reigning champion already has a loss. The next issue follows every response.</p></section><nav className="issue-nav" aria-label="Issue navigation"><span>← Previous issue</span><Link href="/archive">View the archive</Link><span>Next issue →</span></nav></main>; }
